name: agilizai_app
services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ../:/var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=agilizai
      - DB_USERNAME=agilizai
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: agilizaai
      MYSQL_USER: agilizaai
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  dbdata:
